- name: Copy artifact to server
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract the zipped
  shell: |
    cd home/ubuntu
    tar -xzvf artifact.tar.gz -C .

- name: Executing
  become: true
  shell: |
    sudo npm install
    sudo pm2 stop default
    sudo pm2 start npm -- start