- name: Copy artifact into server
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/udacity/artifact.tar.gz

- name: extract zip
  shell: |
    cd home/udacity
    tar -xzvf artifact.tar.gz -C.

- name: Executing
  become: true
  shell: |
    cd /home/udacity
    npm install
    pm2 stop default
    pm2 start npm -- start